project:
  type: website

website:
  title: "STAT 375"
  description: "STAT 375: Teaching Statistics and Data Science at UC Berkeley"
  site-url: "https://stat375.github.io/course-materials/"

  search: false
  page-navigation: true
  opengraph: true

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2022, Andrew Bray"

  sidebar:
    logo: "assets/images/stat-375-hex.png"
    pinned: true
    align: center
    tools:
      - icon: chat-left-text
        href: https://edstem.org/us/courses/19893/discussion/
        text: "Ed Discussion Forum"
      - icon: bank
        href: https://bcourses.berkeley.edu/courses/1514250
        text: "bCourses Site"

    style: "floating"
    search: false
    collapse-level: 2
    contents:
      - href: index.qmd
        text: "Overview"
      - href: syllabus.qmd
        text: "Syllabus"
      - section: "Topics"
        contents:
          - href: weeks/welcome-to-class-site.qmd
            text: "Welcome to Class"
          - href: weeks/teaching-as-a-team-site.qmd
            text: "Teaching as a Team"
          # - href: weeks/how-we-think-site.qmd
          #   text: "The Limits of Working Memory"
          # - href: weeks/creating-an-inclusive-classroom-site.qmd
          #   text: "Creating an Inclusive Classroom"
          # - href: weeks/how-to-teach-without-lecturing-site.qmd
          #   text: "How to Teach Without Lecturing"
          # - href: weeks/lesson-planning-site.qmd
          #   text: "Lesson Planning"
          # - href: weeks/teaching-observations-site.qmd
          #   text: "Teaching Observations"
          # - href: weeks/think-before-you-compute-site.qmd
          #   text: "Think Before You Compute"
          # - href: weeks/assessments-site.qmd
          #   text: "Assessments"
          # - href: weeks/academic-misconduct-site.qmd
          #   text: "Academic Misconduct"


format:
  html:
    theme: [litera]
    mainfont: "Avenir"
    code-copy: true
    code-overflow: wrap
    toc: true