---
title: "Academic Misconduct"
editor: visual
---

## Assignment

### Part 1 - Reading for next class

Please write a comment to Ed that captures your thoughts on this article: [Dan Ariely on 'The Honest Truth About Dishonesty.](https://knowledge.wharton.upenn.edu/article/dan-ariely-dishonestys-slippery-slope/)' Some questions that you're welcome to use to prompt your comment:

-   What did you think of the story of honor code violations at Duke and what Grant calls the classic question of retribution versus deterrence?
-   Ariely discusses how the students may have gotten a harsher punishment than they deserved on an individual basis but that the benefits were considerable for the institution. Do you agree with the decision the University took?
-   Does the course you're teaching have a "serious" code of conduct?
-   Do you agree with your course's code of conduct? Do you think it should be more or less serious?

As always, if there are ample comments already on Ed when you go to start the assignment, please consider replying to existing comments instead of posting a new one.

### Part 2 - Reflection on Academic Misconduct

Your answers to the following will be kept confidential and no action will be taken as a result. We will use these answers to generate discussion on Monday. If you're comfortable with us sharing your story anonymously, please say so in your text response.

-   What is the closest you've gotten to academic misconduct? Have you ever been unsure of whether or not you've engaged in academic misconduct? Have you ever violated a code?
-   Have you ever observed academic misconduct before? Did you report it or let it slide? What led you to report it or not?

## Class Session

The slides used in the class session are linked below.

🖥[Academic Misconduct](../slides/academic-misconduct-slides-speaker.html)


