---
title: "Creating an Inclusive Classroom"
editor: visual
---

## Assignment

## Part 1- Reading for next class

Please read the [short editoria](https://www.tandfonline.com/doi/full/10.1080/26939169.2021.1906555)l by Jeff Witmer, the Editor of the Journal of Statistics and Data Science education on Inclusivity in Statistics. Then, select one of the resources he lists at the end of the piece and read through it (they're also brief). Please write a comment to Ed that captures your thoughts on these pieces. Some questions that you're welcome to use to prompt your comment:

Did anything in this piece surprise you? Are there any components of creating an inclusive statistics classroom that you think the piece leaves out? Have you already changed the way you talk about or teach statistics in light of the considerations that the piece raises? Would you consider changing them? Why or why not? What does the piece do well - what remarks really hit home for you? Where does the piece miss the mark? As always, if there are ample comments already on Ed when you go to start the assignment, please consider replying to existing comments instead of posting a new one.

## Part 2 - Reflection on exclusion

Please reflect back on your experience as a student - either in high school, college, or graduate school. Describe a time that you felt excluded from the classroom or learning environment. Exclusion can take many forms: it can be a mild feeling that you maybe don't belong there or a more acute sense of threat or intimidation. What characteristics of the classroom environment, the instructor and fellow students and their behavior, do you think contributed to this feeling?

We will be sharing a selection of these stories anonymously in class, so in your response, please indicate if prefer that your submission not be shared.

**To reiterate, there are two components to this assignment: the first part should be submitted on Ed, and the second part should be submitted on bCourses.**

## Class Session

The slides used in the class session are linked below.

🖥[Creating an Inclusive Classroom](../slides/creating-an-inclusive-classroom-slides.qmd)
