---
title: "Week 3: The Limits of Working Memory"
editor: visual
---

## Assignment

This week there is no bCourses assignment, only readings with follow-up comments on Ed. I encourage you to enter a dialog with other students by commenting on their posts as an alternative to leaving your own new comment.

There are two readings this week:

-   "Knowledge is Essential to Reading Comprehension" in Ch. 2 of Willingham (the entire selection attached)

-   Either the technical or non-technical follow-up to a component of the reading last week on curiosity. You're of course welcome to look at both, but also welcome to follow your... curiosity.

    -   curosity-technical.pdf

    -   curiosity-non-technical.pdf

Please comment on Ed with your take on these readings. If you're fishing around for a direction to take, have a look at the prompts from the last assignment.

## Class Session

The slides used in the class session are linked below.

<div>

```{=html}
<iframe class="slide-deck" src="How-We-Think-speaker.html"></iframe>
```

</div>
