---
title: "Teaching Observations"
editor: visual
---

## Assignment

Over the next two weeks , you'll be conducting a teaching observation of another GSI and be observed by that same GSI. The observation cycle includes:

1.  Find another GSI to pair with. Many of you got paired up in class, but if you didn't, please reply to this thread with the times that you are teaching so that everyone can find a pair.
2.  Each member of the pair needs to fill out this form.
3.  Share your answer to the last question on the form (about the "focus question") with your partner in advance of your observation.
4.  Observe one another using the form linked below. The observers' notes will go in the left column. Be sure both observations are done and the forms filled out before 4/4.
5.  In class on 4/4 there will be time to debrief both of the observations, so bring your form with the left column filled in, which you'll pass off to the instructor. Your assignment for that week will be to fill in the reflection column.

### After Observations

### Part 1 - Teaching Observation Debrief Reflection

Now that you've had the opportunity to debrief with your partner about your teaching observation, this assignment asks you to reflect on the process. Here are some guiding questions:

What were the main areas of improvement that were suggested by your partner?

Is there anything your partner noted about your teaching that you were surprised by or previously unaware of?

Recall that you started this process by thinking of a "focus question"---what will your focus question be for the next round of observations? How will you address the suggestions you received from your observation?

Please answer on bCourses in \~2 paragraphs.

### Part 2 - Teaching Observations Form Upload

Please upload your teaching observations form to bCourses, in the assignment labeled "Assignment 8 - Teaching Observations Upload."

## Class Session

The slides used in the class session are linked below.

🖥[Teaching Observations](../slides/teaching-obs-discussion-slides.qmd)

