---
title: "Week 2: Teaching as a Team"
editor: visual
---

## Assignment

### Readings

Read the first chapter from, *Why Students Don't Like School* by Daniel T. Willingham, posted to bCourses.

Afterwards, please post to Ed your thoughts (a paragraph or two) on the reading selection. The questions below might be helpful to spur your thinking.

Possible questions to address: 1. Does this reading resonate with your own experience or contrast with it? In what ways? 2. What are a few critiques one would make of the arguments presented? 3. How do the ideas present inform how you might change your teaching?

In place of posting a new comment, you can also reply to your fellow students' comments. Any engagement and input is welcome as long as it's original and respectful.

### Reflections

The topic for next class is "Teaching as a member of a team", so in preparation, please reflect on the role you play as a (u)GSI in a paragraph for two for the question below. The second question is meant to be answered by your instructor, so please ask them for a few sentences about how they see the role of the GSI in their class.

Note: if you know of other students in 375 that are also GSIing for the same class, coordinate your question so the instructor only has to answer once (and then send that answer around to your fellow GSIs). Also, if the instructor has spelled this out previous to you verbally or in writing, you're welcome to transcribe that.

If possible, write your answer to 1 before hearing the instructor's response in 2.

#### 1. From the GSI

What do you think your role is as a GSI in the broader context of the course? What responsibilities do you have to your students? What responsibilities do you have towards your instructor?

#### 2. From the Instructor

What do you see as the role of GSI in the broader context of the course? What responsibilities do they have to the students? What responsibilities do you have towards you?

## Class Session

The slides used in the class session are linked below.

🖥[Teaching as a Team](slides.html)

<div>

```{=html}
<iframe class="slide-deck" src="slides-speaker.html"></iframe>
```

</div>
