---
title: "Academic Misconduct"
subtitle: "STAT 375 UC Berkeley"
logo: "../assets/images/stat-375-hex.png"
format: 
  revealjs:
    theme: "../assets/css/stat20.scss"
    multiplex: true
    transition: fade
    slide-number: true
    incremental: true 
editor: visual
execute:
  freeze: auto
---

## Agenda

1.  Dan Ariely: The Truth About Dishonesty

    -   Why we cheat

2. Guest Speaker from the Center for Student Conduct  

3. Case Studies from the Class

## The Truth About Dishonesty

<center>

<iframe src="https://www.youtube.com/watch?v=kyHLdpma3nQ" width="600px" height="450px">

</iframe>

</center>

## "Fudge" Factors

1.  Everyone else is doing it
2.  You deserve it
3.  For others

::: footer
Reference: Dan Ariely
:::

## Discussion

>
Imagine you learn that one of your students has cheated. What responses do you think they would give if you asked why they cheated? Which fudge factors are behind those reasons (if any)?

# Guest Speaker from the Center for Student Conduct 


## Case Studies from the Class


::: notes
- Can populate with examples from the assignment 
-   Many u/GSIs expressed hesitation over reporting cheaters. Further discussion into what drives this would be interesting.
-   Further discussion into u/GSIs' perspectives on the spectrum of cheating would be interesting. Some acts are more egregious than others; how do we think about this?
:::
