---
title: "Welcome to Class"
subtitle: "STAT 375 UC Berkeley"
logo: "../assets/images/stat-375-hex.png"
format: 
  revealjs:
    theme: "../assets/css/slides.scss"
    multiplex: true
    transition: fade
    slide-number: true
    incremental: true 
editor: visual
execute:
  freeze: auto
---

```{r setup}
#| include: false
library(countdown)
knitr::opts_chunk$set(
  fig.width = 8,
  fig.asp = 0.618,
  fig.retina = 3,
  dpi = 300,
  out.width = "80%"
)
```

# Welcome

## Announcements

-   New on the course website: [FAQ](/course-faq.html)
-   New communication tool: Slack
    -   Find the invite link in your inbox / on Sakai announcements
    -   Use #general for questions, #random for random 🤪
    -   Use code formatting for for questions involving code (see Course FAQ for a demo video)
-   My office hours: All virtual for now, hope to move 1 hour / week to in person later in the semester

## Hybrid teaching {.smaller}

-   Lectures:
    -   In person as long as university says so (and I don't have COVID)
    -   If you can't be in class (and you're well enough to follow along), watch live (or the recording later) on [Panopto](https://duke.hosted.panopto.com/Panopto/Pages/Sessions/List.aspx#folderID=%22d6c1d58a-cb6d-4732-9d4b-ae0c011bf767%22)
    -   Watching live and have questions? Post on Slack!
    -   In class and see someone ask a question on Slack? Please raise it to me!
-   Labs:
    -   Not live streamed / recorded
    -   Lab 2 (next Monday) - individual
    -   Lab 3 onwards - in teams, if teammates are in isolation, set up team Zoom calls
