---
title: "Teaching Statistics and Data Science"
subtitle: "STAT 375 UC Berkeley"
logo: "../assets/images/stat-375-hex.png"
format: 
  revealjs:
    theme: "../assets/css/slides.scss"
    multiplex: true
    transition: fade
    slide-number: true
    incremental: true 
editor: visual
execute:
  freeze: auto
---

```{r setup}
#| include: false
library(countdown)
knitr::opts_chunk$set(
  fig.width = 8,
  fig.asp = 0.618,
  fig.retina = 3,
  dpi = 300,
  out.width = "80%"
)
```

## Agenda

1.  Introductions

2.  Course Structure

3.  Community Standards

4.  Asking Why

5.  Break

6.  GSI Panel

# Meet your group

-   In your breakout rooms, take turns introducing yourselves and sharing:
    -   Your name and preferred pronouns
    -   Your year and major
    -   What class you are teaching
    -   Memory of your best teacher and what made them so effective
-   You have 8 minutes

# Introductions

# Course Structure

View syllabus on Ed.

# Course Timeline

Each week:

**Monday**: meet for 1.5 - 2 hrs

**Wednesday**: assignments available on bCourses

**Sunday 8 pm**: assignments due on bCourses

Assignments generally feature reflections on the previous week and readings for the coming week.

# Community Standards

In your breakout rooms, please agree upon:

1.  Three adjectives that describe a class environment is **conducive** to everyone learning
2.  Three adjectives that describe a class environment that is **not conducive** to everyone learning

Then post them to the padlet:

https://padlet.com/andrewbray1/oykqvd86obxx9bfh

You will have 8 minutes.

# Course Goals

> Train the habit of asking *why* you are teaching something one way or another.

> Judge your teaching not by your knowledge of statistics / data science, but by your student's.

# Critique of this class so far...

## 

What worked? What didn't? How can we change it?

::: columns
::: {.column width = "50%"} \### Meet your group - What was the goal? - How big should the groups be? - Which questions?

### Introductions

-   How personal should you be?
:::

::: {.column width = "50%"} \### Syllabus - What were your main takeaways? - How else could this information be presented?

### Community Standards

-   What was the feel of the group discussion?
-   Was everyone participating? :::

::::

# Break until 3:15

# GSI Panel

### Isaac Schmidt

### Chad Breece
