---
title: "The Limits of Working Memory HW"
editor: visual
---

## Assignment

## Part 1

This week there is no bCourses assignment, only readings with follow-up comments on Ed. I encourage you to enter a dialog with other students by commenting on their posts as an alternative to leaving your own new comment.

There are two readings this week:

-   "Knowledge is Essential to Reading Comprehension" in Ch. 2 of Willingham (the entire selection attached)

-   Either the technical or non-technical follow-up to a component of the reading last week on curiosity. You're of course welcome to look at both, but also welcome to follow your... curiosity.

    -   curosity-technical.pdf

    -   curiosity-non-technical.pdf

Please comment on Ed with your take on these readings. If you're fishing around for a direction to take, have a look at the prompts from the last assignment.

##Part II

Please read the introductory chapter in, "Why Don't Students Like School?" by Daniel T. Willingham.

Afterwards, please post to Ed your thoughts (a paragraph or two) on the reading selection. The questions below might be helpful to spur your thinking.

Possible questions to address: 1. Does this reading resonate with your own experience or contrast with it? In what ways? 2. What are a few critiques one would make of the arguments presented? 3. How do the ideas present inform how you might change your teaching?

In place of posting a new comment, you can also reply to your fellow students' comments. Any engagement and input is welcome as long as it's original and respectful.
